const quotes = [
  "The secret of getting ahead is getting started.",
  "Don’t watch the clock; do what it does. Keep going.",
  "It always seems impossible until it’s done.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Believe you can and you're halfway there.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream bigger. Do bigger.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Don’t wait for opportunity. Create it.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "Dream it. Wish it. Do it.",
  "Success is what happens after you have survived all your mistakes.",
  "Don’t limit your challenges. Challenge your limits.",
  "The way to get started is to quit talking and begin doing.",
  "Don’t be afraid to give up the good to go for the great.",
  "If you want to achieve greatness stop asking for permission.",
  "Do what you can with all you have, wherever you are.",
  "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
  "Work hard in silence, let your success be your noise.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "Discipline is the bridge between goals and accomplishment.",
  "The future depends on what you do today.",
  "The key to success is to focus on goals, not obstacles.",
  "Doubt kills more dreams than failure ever will.",
  "If you get tired, learn to rest, not to quit.",
  "Make each day your masterpiece.",
  "A goal without a plan is just a wish.",
  "If you can dream it, you can do it.",
  "Opportunities don’t happen. You create them.",
  "Your limitation—it’s only your imagination.",
  "Sometimes later becomes never. Do it now.",
  "Don’t wait for inspiration. Be the inspiration.",
  "You don’t have to be great to start, but you have to start to be great.",
  "If you want to lift yourself up, lift up someone else.",
  "Keep your eyes on the stars and your feet on the ground.",
  "The man who moves a mountain begins by carrying away small stones.",
  "Do one thing every day that scares you.",
  "The best way to predict the future is to create it.",
  "Start where you are. Use what you have. Do what you can.",
  "Failure is simply the opportunity to begin again, this time more intelligently.",
  "Action is the foundational key to all success.",
  "Don’t let what you cannot do interfere with what you can do.",
  "In the middle of every difficulty lies opportunity.",
  "You don’t find willpower, you create it.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Don’t count the days, make the days count.",
  "You are never too old to set another goal or to dream a new dream.",
  "Be so good they can’t ignore you.",
  "You miss 100% of the shots you don’t take.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "If you’re going through hell, keep going.",
  "Perseverance is not a long race; it is many short races one after another.",
  "Focus on being productive instead of busy.",
  "Don’t let yesterday take up too much of today.",
  "Make your life a masterpiece; imagine no limitations on what you can be, have or do.",
  "Act as if what you do makes a difference. It does.",
  "Stay hungry, stay foolish.",
  "Don’t be afraid to start over. It’s a chance to build something better this time.",
  "You can’t go back and change the beginning, but you can start where you are and change the ending.",
  "If you want something you’ve never had, you must be willing to do something you’ve never done.",
  "Don’t wish it were easier. Wish you were better.",
  "When you feel like quitting, think about why you started.",
  "A little progress each day adds up to big results.",
  "Be stronger than your excuses.",
  "Don’t let small minds convince you that your dreams are too big.",
  "Do it with passion or not at all.",
  "Difficulties in life are intended to make us better, not bitter.",
  "Your passion is waiting for your courage to catch up.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "You are capable of amazing things.",
  "Everything you can imagine is real.",
  "Stay positive, work hard, make it happen.",
  "Don’t let the fear of losing be greater than the excitement of winning.",
  "Don’t tell people your plans. Show them your results.",
  "Winners are not those who never fail, but those who never quit.",
  "Great things take time.",
  "Learn as if you will live forever, live like you will die tomorrow.",
  "Sometimes you win, sometimes you learn.",
  "Every accomplishment starts with the decision to try.",
  "You didn’t come this far only to come this far.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Failure will never overtake me if my determination to succeed is strong enough.",
  "It’s not the load that breaks you down, it’s the way you carry it.",
  "The difference between ordinary and extraordinary is that little extra.",
  "You are what you do, not what you say you’ll do.",
  "Motivation gets you started. Habit keeps you going.",
  "When you want to succeed as bad as you want to breathe, then you’ll be successful.",
  "Don’t just dream about success. Work for it.",
  "Keep grinding. Your time will come.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "Dare to be different.",
  "Success is the sum of small efforts repeated day in and day out.",
];

const heading = document.querySelector("h3");
const button = document.querySelector("button");

button.addEventListener("click", () => {
  heading.innerText = quotes[Math.floor(Math.random() * quotes.length - 1)];
});
